version: "3"

services:

   fleetman-webapp:
      image: nhuallpa/fletman-webapp
      networks:
        - fleetman-network
      ports:
        -80:8080
   
   database:
      image: mysql:5
      networks:
        - fleetman-network
      enviroments:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=fleetman
networks:
   fleetman-network: